### ISSUE TITLE
Code blocks won't render

### ISSUE THREAD

**Issue by binyamin** [bookwyrm-social/documentation#1]
Compare the source content with the live site

https://github.com/bookwyrm-social/documentation/blob/bc50051fcf38fc539b3593f212e190b92d0b9d0c/content/running_bookwyrm/install-prod.md#L53-L65
![image](https://user-images.githubusercontent.com/39805353/114626210-5d99b200-9c81-11eb-8822-bfe3db3cbf89.png)

**Comment by mouse-reeve** [comment]
Thank you! I accidentally pushed the fix directly to main instead of closing this with a PR like I meant to, but it should be fixed on prod now :)
