### ISSUE TITLE
External Storage instructions work with Linode/Akamai

### ISSUE THREAD

**Issue by biglifedecision** [bookwyrm-social/documentation#109]
When I first installed bookwyrm, I could not get External Storage to work with Linode (now called Akamai)'s object storage. I followed the instructions, and tried various tweaks based on previous experience using Linode's Object Storage in place of AWS S3 for other things, but nothing worked.

Now I am running bookwyrm 0.6.4 and decided to try setting it up again. This time following the instructions in the bookwyrm documentation worked perfectly. yay!

**Comment by mouse-reeve** [comment]
Just to clarify, what is the change needed here? It sounds like things are working?

**Comment by biglifedecision** [comment]
I was following the guidance: 

>If you use another service, please share your experience (especially if you had to take different steps) by filing an Issue on the [BookWyrm Documentation](https://github.com/bookwyrm-social/documentation) repository.

to make a positive report. However I've realized that there is a CORS issue preventing the fonts from loading. Linode requires a `.xml` CORS file rather than `.json`, so I had to make that manually (which is a change that could be mentioned in the Documentation to cover some service providers). But, currently it's not working for me, since fonts are not loading. This is my first time really debugging an issue like this, if I figured out what is needed for a `.xml` CORS file to use Linode I will report it here!

**Comment by mouse-reeve** [comment]
Thank you, it would be great to point people who also need that kind of CORS file in the right direction.

**Comment by biglifedecision** [comment]
after some thorough digging, it seems that the instructions as-is work perfectly fine for Linode! the `./bw-dev set_cors_to_s3 cors.json` command correctly installs the desired CORS policy. 

whatever issue I was having seems to be browser-specific. so this Issue is back to the original intention: External Storage instructions work just fine with Linode/Akamai !
