### ISSUE TITLE
Local Dev first setup should mention turning off https to prevent CSRF problems

### ISSUE THREAD

**Issue by mattkatz** [bookwyrm-social/documentation#111]
When I follow the current instructions I get all the way through and find that I can't do https connections to my local machine.
Http seems to work though.
When I register with the admin key, I get  blocked because of a CSRF warning.

I found that if I go into the .env and change `USE_HTTPS=true` to `USE_HTTPS=false` I am able to complete initial admin account registration.

**Comment by hughrun** [comment]
fixed by @mattkatz :)
