### ISSUE TITLE
Error deploying docs site

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/documentation#121]
Hi @bookwyrm-social/code-review if someone smarter than me can work out why this is happening I would be most grateful!

Per [the last PR that I pulled in](https://github.com/bookwyrm-social/documentation/pull/120), we have a new GitHub action to build the site before it is deployed to the web server (previously it just deployed, without rebuilding). All is well, until we run `python generate.py` which should compile the site including translations, [but instead we get](https://github.com/bookwyrm-social/documentation/actions/runs/6942496321/job/18885569380):

```sh
Generating site/moderation.html
  File "/home/runner/work/documentation/documentation/generate.py", line 150, in <module>
    data = get_site_data(SLUG, locale["code"], content_path)
  File "/home/runner/work/documentation/documentation/generate.py", line 76, in get_site_data
    subcategories.sort(key=lambda v: v.get("Order", -1))
TypeError: '<' not supported between instances of 'str' and 'int'
Generating site/updating.html
```

**I cannot replicate this error on my local machine**, and I can't work out where the `str` might be coming from - I assume this should `sort` each subcategory by `Order` value.

**Comment by dato** [comment]
I took a look. The German version of updating.md has invalid metadata, introduced a while ago in https://github.com/bookwyrm-social/documentation/commit/970d9d94f82b944a30e0e94b1b92a54894114698 (see first line, adds bogus "`CONTEXTREQUEST`").

This commit is not in main, but in the l10n_main branch that `./bw-dev messages:update` brings. (I think it should be possible to reproduce this locally running that command first.)

I'm not sure how to get the fix in a permanent fashion on the branch (do it through Crowdin?), but if you comment out the `messages:update` step, the action ought to generate the site successfully (tested on my fork).

**Comment by hughrun** [comment]
Oh nice catch @dato! @mouse-reeve do you have any ideas about where we should fix this? Obviously I could just make a change in`l10n_main` but presumably that will be overwritten by Crowdin at some point?

**Comment by mouse-reeve** [comment]
You should be able to fix it in Crowdin, and then after it's had a couple hours to sync, the l10n branch will reflect the change

**Comment by hughrun** [comment]
Ohhh LOL I've never even looked at the translation link because I'm monolingual. Ok I temporarily updated the l10n branch manually, and now I've adjusted it in Crowdin too.
