### ISSUE TITLE
Installing in Production page - using a reverse proxy 404 not found

### ISSUE THREAD

**Issue by judicandus** [bookwyrm-social/documentation#71]
Hello, I'm following the instructions on https://docs.joinbookwyrm.com/install-prod.html to start my own bookwyrm instance. 

In the nginx configuration section it mentions to look at https://docs.joinbookwyrm.com/using-a-reverse-proxy.html if there is another web server running, however the page does not exist. 

The file exists so I think it's just a matter of correcting the web page link?

https://github.com/bookwyrm-social/documentation/blob/main/content/running_bookwyrm/reverse-proxy.md

**Comment by mouse-reeve** [comment]
Oops, I thought I caught all of these! Thanks for pointing this out.
